config/routes.rb
Rails.application.routes.draw do
  root 'kvitters#top'
  
  resources :kvitters do
    collection do
      post :confirm
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/kvitter.rb
class Kvitter < ApplicationRecord
  validates :content, length: {in: 1..140}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/kvitters_controller.rb
class KvittersController < ApplicationController
  before_action :set_kvitter, only: [:show, :edit, :update, :destroy]
  
  def index
    @kvitters= Kvitter.all
  end
  
  def new
    if params[:back]
      @kvitter = Kvitter.new(kvitter_params)
    else
      @kvitter = Kvitter.new
    end
  end
  
  def create
    @kvitter = Kvitter.new(kvitter_params)
    if @kvitter.save
      redirect_to kvitters_path, notice: "つぶやきを作成しました！"
    else
      render 'new'
    end  
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    if @kvitter.update(kvitter_params)
      redirect_to kvitters_path, notice: "つぶやきを編集しました！"
    else
      render 'edit'
    end
  end
  
  def destroy
    @kvitter.destroy
    redirect_to kvitters_path, notice: "つぶやきを削除しました！"
  end
  
  def confirm
    @kvitter = Kvitter.new(kvitter_params)
    render :new if @kvitter.invalid?
  end
  
  private
  def kvitter_params
    params.require(:kvitter).permit(:content)
  end

  def set_kvitter
    @kvitter = Kvitter.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kvitters_helper.rb
module KvittersHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_kvitters_path
    elsif action_name == 'edit'
      kvitter_path
    end
  end
end

app/views/kvitters/_form.html.erb
<%= form_with(model: @kvitter, local: true, url: choose_new_or_edit) do |form| %>
  <% if @kvitter.errors.any? %>
    <div class="alert alert-danger" role="alert">
      <div id="error_explanation">
        <h2><%= @kvitter.errors.count %>件のエラーがあります。</h2>
        <ul>
        <% @kvitter.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>
  <div class="input_area"><%= form.text_area :content, :size=>"100×60" %></div>
  <div class="submit_button">
    <input class="btn btn-primary" type="submit" value="投稿">
  </div>
<% end %>

<%= link_to "つぶやき一覧表示", kvitters_path %>

app/views/kvitters/confirm.html.erb
<h3>以下の内容で投稿する</h3>

<%= form_with(model: @kvitter, url: kvitters_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>

  <p>内容:<%= @kvitter.content %></p>
  <%= form.submit  "投稿" %>
<% end %>

<%= form_with(model: @kvitter, url: new_kvitter_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :content %>
  <%= form.submit "もどる", name: 'back' %>
<% end %>

app/views/kvitters/edit.html.erb
<h1>編集する</h1>

<%= render 'form' %>

app/views/kvitters/index.html.erb
<h1>つぶやき一覧</h1>

<p><%= notice %></p>

<% @kvitters.each do |kvitter| %>
<ul class="row_1">
  <li class="col-sm-12 col-md-4">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h4 class="panel-title">（アカウント）</h4>
      </div>
      <div class="panel-body">
        <p><%= kvitter.content %></p>
        <p class="button_area">
          <button type="button" class="btn btn-warning"><%= link_to '編集',edit_kvitter_path(kvitter.id),data: { confirm: '本当に編集していいですか？' } %></button>
          <button type="button" class="btn btn-danger"><%= link_to '削除',kvitter_path(kvitter.id),method: :delete,data: { confirm: '本当に削除していいですか？' } %></button>
        </p>
      </div>
      </div>
  </li>
</ul>
<% end %>

app/views/kvitters/new.html.erb
<h1>つぶやく</h1>

  <%= render 'form' %>

app/views/kvitters/top.html.erb
  <div>
    <img src="<%= asset_path "birds.png" %>" class="image_area">
  </div>
  <section class="about">
    <h1>KVITTER</h1>
    <p>
      KVITTERは、twitterをモデルに練習で作成したアプリです
    </p>
  </section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Cloneapp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <ul>
        <li class="home"><a href="/">KVITTER</a></li>
        <li><a href="/kvitters">つぶやき一覧</a></li>
        <li><a href="/kvitters/new">新規つぶやき</a></li>
      </ul>
    </header>
    
    <%= yield %>
    
    <footer class="footer">
      <div class="footer_content">
        <p>PHASE2課題 KAKIKI Kunie</p>
      </div>
    </footer>

    
  </body>
</html>